name: Lint and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Test
    runs-on: [ubuntu-latest]
    continue-on-error: false

    steps:
      # Setup Python 3.11
      - name: Setup Python 3.11
        id: python_setup
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      # Setup Terraform
      - name: Setup Terraform
        id: terraform_setup
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "1.13.3"
          terraform_wrapper: true

      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      # Run Linting
      - name: Run Linting
        id: linting
        run: |
          echo "Install dependencies"
          python3 -m pip install -r requirements.txt -q

          echo "Initialize Git"
          git init
          git add *

          echo "Run pre-commit"
          python3 -m pre_commit install --install-hooks
          python3 -m pre_commit run --all-files --verbose
